"""Project-wide invariants fixed at S0."""

PROJECT_NAME = "CycAMP-FusionDemo"
STANDARD_AMINO_ACIDS = frozenset("ACDEFGHIKLMNPQRSTVWY")
TOTAL_UNIQUE_LIMIT = 10_000
CYCLIC_CORE_LIMIT = 2_500
PRETRAIN_LIMIT = 7_500
MIC_THRESHOLD_UG_ML = 25.0
DEFAULT_RANDOM_SEED = 42

